spring:
  datasource:
    name: mysql
    url: jdbc:mysql://localhost/book_management
    username: root
    password: 107107
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置映射文件
  type-aliases-package: com.example.campus.navigation.entity

server:
  port: 8083
  servlet:
    context-path: /back

